apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "spring-boot-postgres.fullname" . }}-servicemonitor
  namespace: {{ .Values.monitoring.namespace | default "monitoring" }}
  labels:
    release: monitoring   
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: {{ .Chart.Name }}
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
